# Generated by Django 6.1.1 on 2026-10-02 14:34

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_historicaluser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.RoleAwareUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Students'), ('TEACHER', 'Teachers & Advisors'), ('PARENT', 'Parents'), ('OBSERVER', 'Observers'), ('ADMIN', 'Admins'), ('STAFF', 'Staff')], default='OBSERVER', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Students'), ('TEACHER', 'Teachers & Advisors'), ('PARENT', 'Parents'), ('OBSERVER', 'Observers'), ('ADMIN', 'Admins'), ('STAFF', 'Staff')], default='OBSERVER', max_length=20),
        ),
    ]
