# Generated by Django 6.1.1 on 2026-09-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='frn',
            field=models.CharField(blank=True, db_index=True, help_text='Family Reference Number - shared by siblings.', max_length=20, verbose_name='FRN'),
        ),
    ]
