# Generated by Django 6.1.1 on 2026-09-30 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_numbering_format', models.CharField(choices=[('GRADE_11_12', 'Grade 11 & 12'), ('YEAR_12_13', 'Year 12 & 13')], default='YEAR_12_13', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='YearLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='academics.curriculumframework')),
            ],
            options={
                'ordering': ['framework__order', 'order'],
                'unique_together': {('framework', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GradeLevelTrackMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('custom_label', models.CharField(blank=True, max_length=100)),
                ('grade_level', models.ForeignKey(blank=True, help_text='Optional link to the enrollment-facing grade level, once reconciled with real class data.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_mappings', to='academics.gradelevel')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_mappings', to='academics.curriculumtrack')),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_mappings', to='academics.yearlevel')),
            ],
            options={
                'ordering': ['year_level__order', 'track__framework__order', 'track__order'],
                'unique_together': {('year_level', 'track')},
            },
        ),
    ]
