# Generated by Django 6.1.1 on 2026-10-02 06:33

import django.db.models.deletion
from django.db import migrations, models


def copy_school_format_to_academic_years(apps, schema_editor):
    AcademicYear = apps.get_model('academics', 'AcademicYear')
    SchoolSetting = apps.get_model('academics', 'SchoolSetting')
    setting = SchoolSetting.objects.filter(pk=1).first()
    if setting:
        AcademicYear.objects.all().update(grade_numbering_format=setting.grade_numbering_format)


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_curriculumframework_schoolsetting_yearlevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='grade_numbering_format',
            field=models.CharField(choices=[('GRADE_11_12', 'Grade 11 & 12'), ('YEAR_12_13', 'Year 12 & 13')], default='YEAR_12_13', max_length=20),
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='next_grade_level',
            field=models.ForeignKey(blank=True, help_text='Suggested destination when promoting students to the next academic year.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_levels', to='academics.gradelevel'),
        ),
        migrations.RunPython(copy_school_format_to_academic_years, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='SchoolSetting',
        ),
    ]
