# Generated by Django 6.1.1 on 2026-10-02 07:18

import django.db.models.deletion
import re
from django.db import migrations, models


def move_grade_links_to_year_levels(apps, schema_editor):
    GradeLevel = apps.get_model('academics', 'GradeLevel')
    GradeLevelTrackMapping = apps.get_model('academics', 'GradeLevelTrackMapping')
    YearLevel = apps.get_model('academics', 'YearLevel')
    alias = schema_editor.connection.alias

    levels = {level.id: level.name for level in YearLevel.objects.using(alias).all()}
    labels_by_level = {level_id: {name} for level_id, name in levels.items()}
    explicit_level_ids = {}
    for mapping in GradeLevelTrackMapping.objects.using(alias).all():
        if mapping.custom_label:
            labels_by_level[mapping.year_level_id].add(mapping.custom_label)
        if mapping.grade_level_id:
            explicit_level_ids.setdefault(mapping.grade_level_id, set()).add(mapping.year_level_id)

    for grade in GradeLevel.objects.using(alias).all():
        explicit = explicit_level_ids.get(grade.id, set())
        if len(explicit) == 1:
            grade.year_level_id = explicit.pop()
        elif not explicit:
            candidates = {
                level_id
                for level_id, labels in labels_by_level.items()
                if any(re.match(rf'^{re.escape(label)}(?!\d)', grade.name) for label in labels)
            }
            if len(candidates) == 1:
                grade.year_level_id = candidates.pop()
        if grade.year_level_id:
            grade.save(update_fields=['year_level'])


def restore_grade_links(apps, schema_editor):
    GradeLevel = apps.get_model('academics', 'GradeLevel')
    GradeLevelTrackMapping = apps.get_model('academics', 'GradeLevelTrackMapping')
    alias = schema_editor.connection.alias
    for mapping in GradeLevelTrackMapping.objects.using(alias).all():
        mapping.grade_level_id = GradeLevel.objects.using(alias).filter(
            year_level_id=mapping.year_level_id,
        ).values_list('id', flat=True).first()
        mapping.save(update_fields=['grade_level'])


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_delete_schoolsetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradelevel',
            name='year_level',
            field=models.ForeignKey(blank=True, help_text='Canonical Years & Levels row used for enrollment display and curriculum availability.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_levels', to='academics.yearlevel'),
        ),
        migrations.RunPython(move_grade_links_to_year_levels, restore_grade_links),
        migrations.RemoveField(
            model_name='gradeleveltrackmapping',
            name='grade_level',
        ),
    ]
