# Generated by Django 6.1.1 on 2026-10-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_map_year2_integrated_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradelevel',
            name='next_grade_level',
        ),
    ]
