# Generated by Django 6.1.1 on 2026-10-02 07:36

from django.db import migrations, models


CURRICULUM_OPTIONS = [
    ('cambridge-advanced', 'Cambridge Assessment International Education', 'Cambridge Advanced', 10, True, False, '', ''),
    ('cambridge-igcse', 'Cambridge Assessment International Education', 'Cambridge IGCSE', 20, True, False, '', ''),
    ('cambridge-lower-secondary', 'Cambridge Assessment International Education', 'Cambridge Lower Secondary', 30, True, False, '', ''),
    ('ib-diploma', 'International Baccalaureate', 'IB Diploma', 40, False, False, '', ''),
    ('ib-career-related', 'International Baccalaureate', 'IB Career-related Programme', 50, False, False, '', ''),
    ('ib-middle-years', 'International Baccalaureate', 'IB Middle Years', 60, False, False, '', ''),
    ('ib-primary-years', 'International Baccalaureate', 'IB Primary Years', 70, False, False, '', ''),
    ('pearson-advanced-levels', 'Pearson Edexcel', 'Pearson Edexcel International Advanced Levels', 80, False, False, '', ''),
    ('pearson-btec', 'Pearson Edexcel', 'Pearson BTEC', 90, False, False, '', ''),
    ('pearson-international-gcses', 'Pearson Edexcel', 'Pearson Edexcel International GCSEs', 100, False, False, '', ''),
    ('ica-middle-years', 'International Curriculum Association', 'International Middle Years Curriculum', 110, False, False, '', ''),
    ('ica-primary-curriculum', 'International Curriculum Association', 'International Primary Curriculum', 120, False, False, '', ''),
    ('college-board-ap', 'The College Board', 'Advanced Placement', 130, False, False, '', ''),
    ('national-high-school', 'National Curriculum', 'High School', 140, True, True, 'HS', ''),
    ('national-middle-school', 'National Curriculum', 'Middle School', 150, True, True, 'MS', ''),
    ('national-primary-school', 'National Curriculum', 'Primary School', 160, True, True, 'PS', ''),
]


def seed_key_academic_functions(apps, schema_editor):
    Configuration = apps.get_model('academics', 'AcademicConfiguration')
    Option = apps.get_model('academics', 'AcademicCurriculumOption')
    alias = schema_editor.connection.alias
    Configuration.objects.using(alias).get_or_create(pk=1)
    for code, provider, name, order, enabled, customizable, short_name, full_title in CURRICULUM_OPTIONS:
        Option.objects.using(alias).get_or_create(
            code=code,
            defaults={
                'provider': provider,
                'name': name,
                'order': order,
                'is_enabled': enabled,
                'is_customizable': customizable,
                'short_name': short_name,
                'full_title': full_title,
            },
        )


def unseed_key_academic_functions(apps, schema_editor):
    Configuration = apps.get_model('academics', 'AcademicConfiguration')
    Option = apps.get_model('academics', 'AcademicCurriculumOption')
    alias = schema_editor.connection.alias
    Option.objects.using(alias).filter(code__in=[row[0] for row in CURRICULUM_OPTIONS]).delete()
    Configuration.objects.using(alias).filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_remove_gradelevel_next_grade_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes_enabled', models.BooleanField(default=True)),
                ('parents_association_enabled', models.BooleanField(default=True)),
                ('annotations_enabled', models.BooleanField(default=True)),
                ('term_grade_calculation', models.CharField(choices=[('PERCENTAGE', 'Use Percentage weights'), ('ABSOLUTE', 'Use Absolute weights')], default='PERCENTAGE', max_length=20)),
                ('points_based_averaging', models.BooleanField(default=True)),
                ('year_level_behaviour', models.CharField(choices=[('MATCH_GROUP', 'Match Group Year Level'), ('MATCH_IF_BLANK', 'Match Group Year Level if Blank'), ('PRESERVE', 'Preserve Year Level')], default='MATCH_GROUP', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicCurriculumOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('provider', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=False)),
                ('is_customizable', models.BooleanField(default=False)),
                ('short_name', models.CharField(blank=True, max_length=30)),
                ('full_title', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(seed_key_academic_functions, unseed_key_academic_functions),
    ]
