# Generated by Django 6.1.1 on 2026-10-02 07:52

import django.db.models.deletion
from django.db import migrations, models


ADDITIONAL_OPTIONS = [
    ('cambridge-primary', 'Cambridge Assessment International Education', 'Cambridge Primary', 35),
    ('ieyc-and-cambridge', 'International Early Years Curriculum', 'IEYC and Cambridge', 170),
    ('ieyc', 'International Early Years Curriculum', 'IEYC', 180),
]

CURRICULUM_ALIASES = {
    'cambridge-advanced': ['Cambridge AS'],
}


def connect_existing_curricula(apps, schema_editor):
    AcademicCurriculumOption = apps.get_model('academics', 'AcademicCurriculumOption')
    ClassRoom = apps.get_model('academics', 'ClassRoom')
    Curriculum = apps.get_model('academics', 'Curriculum')
    CurriculumFramework = apps.get_model('academics', 'CurriculumFramework')
    CurriculumTrack = apps.get_model('academics', 'CurriculumTrack')
    GradeLevelTrackMapping = apps.get_model('academics', 'GradeLevelTrackMapping')
    alias = schema_editor.connection.alias
    YearLevel = apps.get_model('academics', 'YearLevel')

    for code, provider, name, order in ADDITIONAL_OPTIONS:
        AcademicCurriculumOption.objects.using(alias).get_or_create(
            code=code,
            defaults={
                'provider': provider,
                'name': name,
                'order': order,
                'is_enabled': False,
                'is_customizable': False,
                'short_name': '',
                'full_title': '',
            },
        )

    options = AcademicCurriculumOption.objects.using(alias).all()
    for option in options:
        curricula_names = CURRICULUM_ALIASES.get(option.code, [option.name])
        for curriculum_name in curricula_names:
            curriculum = Curriculum.objects.using(alias).filter(name=curriculum_name).first()
            if curriculum:
                curriculum.academic_options.add(option)
                if curriculum.enrollments.exists():
                    option.is_enabled = True

        framework = CurriculumFramework.objects.using(alias).filter(name=option.provider).first()
        track = None
        if framework:
            track = CurriculumTrack.objects.using(alias).filter(
                framework_id=framework.id, name=option.name,
            ).first()
        if track:
            track.academic_option_id = option.id
            track.save(update_fields=['academic_option'])
            if GradeLevelTrackMapping.objects.using(alias).filter(track_id=track.id, is_enabled=True).exists():
                option.is_enabled = True

        if option.is_enabled:
            if framework is None:
                framework, _ = CurriculumFramework.objects.using(alias).get_or_create(
                    name=option.provider,
                    defaults={'order': option.order},
                )
            if track is None:
                track, _ = CurriculumTrack.objects.using(alias).get_or_create(
                    framework_id=framework.id,
                    name=option.name,
                    defaults={'order': option.order, 'academic_option_id': option.id},
                )
            if track.academic_option_id != option.id:
                track.academic_option_id = option.id
                track.save(update_fields=['academic_option'])

            for year_level in YearLevel.objects.using(alias).all():
                GradeLevelTrackMapping.objects.using(alias).get_or_create(
                    year_level_id=year_level.id,
                    track_id=track.id,
                    defaults={'is_enabled': False, 'custom_label': ''},
                )

            if not option.curriculums.exists():
                curriculum, _ = Curriculum.objects.using(alias).get_or_create(name=option.name)
                curriculum.academic_options.add(option)

        option.save(update_fields=['is_enabled'])


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_academicconfiguration_academiccurriculumoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='academic_options',
            field=models.ManyToManyField(blank=True, related_name='curriculums', to='academics.academiccurriculumoption'),
        ),
        migrations.AddField(
            model_name='curriculumtrack',
            name='academic_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='academics.academiccurriculumoption'),
        ),
        migrations.RunPython(connect_existing_curricula, migrations.RunPython.noop),
    ]
