# Generated by Django 6.1.1 on 2026-10-02 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_curriculum_academic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='academics.programme'),
        ),
    ]
