# Generated by Django 6.1.1 on 2026-10-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_order_reference_tracks'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='only_one_current_academic_year'),
        ),
    ]
